# Tailscale egress proxy for ClickHouse access
# Allows pods in this cluster to reach ClickHouse on ops-logs-clickhouse cluster
# Reference: https://tailscale.com/kb/1438/kubernetes-operator-cluster-egress
apiVersion: v1
kind: Service
metadata:
  name: clickhouse-egress
  namespace: tailscale
  annotations:
    tailscale.com/tailnet-fqdn: clickhouse-logs.batfish-ray.ts.net
spec:
  type: ExternalName
  externalName: placeholder  # Replaced by Tailscale operator
  ports:
    - name: http
      port: 8123
      protocol: TCP
    - name: native
      port: 9000
      protocol: TCP
