controller:
  replicaCount: 2
  nodeSelector:
    kubernetes.io/os: linux
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 100m
      memory: 256Mi
  admissionWebhooks:
    patch:
      nodeSelector:
        kubernetes.io/os: linux
defaultBackend:
  nodeSelector:
    kubernetes.io/os: linux
