#cloud-config
package_upgrade: true
packages:
  - unattended-upgrades
users:
  - name: freecodecamp
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh_import_id:
      - raisedadead
