#cloud-config
package_upgrade: true
packages:
  - nginx
  - unattended-upgrades
users:
  - name: freecodecamp
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh_import_id:
      - raisedadead
runcmd:
  - rm -rf /etc/nginx
  - git clone https://github.com/freecodecamp/nginx-config /etc/nginx
  - git clone https://github.com/freeCodeCamp/error-pages /var/www/html/error-pages
