---
- name: Check if Docker is installed
  stat:
    path: /usr/bin/docker
  register: docker_installed
  no_log: "{{ variable_no_log | default (true) }}"

- name: Initialize Swarm using the role
  include_role:
    name: docker
    tasks_from: install-swarm.yml
  when: docker_installed.stat.exists == true
