---
- name: Set the Consul version (pin to a specific version)
  set_fact:
    consul_version: 1.17.2

- name: Set fact for amd64 or arm64
  set_fact:
    arch: "{{ (ansible_architecture == 'x86_64') | ternary('amd64', 'arm64') }}"

- name: Install Consul from releases
  unarchive:
    src: https://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{
      consul_version }}_linux_{{ arch }}.zip
    dest: /usr/local/bin
    remote_src: yes
    creates: /usr/local/bin/consul
    owner: root
    group: root
    mode: 0755

- name: Check consul version
  command: consul version
  register: consul_version_output
  changed_when: false
  failed_when: "'Consul v' not in consul_version_output.stdout"

- name: Create a consul group
  group:
    name: consul
    system: yes

- name: Create a consul user
  user:
    name: consul
    group: consul
    comment: "Consul user"
    shell: /bin/false
    system: yes
    create_home: yes
    home: /etc/consul.d

- name: Set the permissions on the consul home directory
  file:
    path: /etc/consul.d
    state: directory
    owner: consul
    group: consul
    mode: 0700

- name: Create a consul certificate directory
  file:
    path: /etc/consul.d/certs
    state: directory
    owner: consul
    group: consul
    mode: 0700

- name: Create a data directory
  file:
    path: /opt/consul
    state: directory
    owner: consul
    group: consul
    mode: 0755
