---
- name: Check if Docker is installed
  stat:
    path: /usr/bin/docker
  register: docker_installed
  no_log: '{{ variable_no_log | default (true) }}'

- name: Check if Consul is installed
  stat:
    path: /usr/bin/consul
  register: consul_installed
  no_log: '{{ variable_no_log | default (true) }}'

- name: Install Consul if not installed using the role
  include_role:
    name: consul
    tasks_from: install-consul.yml
  when:
    consul_installed.stat.exists == false and docker_installed.stat.exists ==
    true

- name: Done Installing
  debug:
    msg:
      'Done Installing Consul, continue to configure with additional playbooks.'
