# IMPORTANT: This file has to be be named linode.yml or linode.yaml
# See: https://github.com/ansible-collections/community.general/blob/011b2f8bdc2a042f0eb44739ff51ce425f391afa/plugins/inventory/linode.py#L274

plugin: community.general.linode # can be replaced with linode.cloud.instance, when they support Jinja2 template strings
access_token: "{{ lookup('env', 'LINODE_API_TOKEN') }}"

groups:
  # Test Instances
  test_all: "'test' in (tags|list)"

  # Staging Instances
  stg_all: "'stg' in (tags|list)"

  # Production Instances
  prd_all: "'prd' in (tags|list)"

  # Operations Instances
  ops_all: "'ops' in (tags|list)"

  # O11y Cluster
  o11y_all: "'o11y' in (tags|list)"
  managers: "'o11y_leader' in (tags|list)"  # TODO: Refactor the naming of this group
  workers: "'o11y_worker' in (tags|list)"   # TODO: Refactor the naming of this group

  # Publish Cluster
  publish_all: "'publish' in (tags|list)"
  publish_leaders: "'publish_leader' in (tags|list)"
  publish_workers: "'publish_worker' in (tags|list)"

  # Oldeworld Cluster -- STG
  stg_oldeworld_all: "'stg' in (tags|list) and 'oldeworld' in (tags|list)"
  stg_oldeworld_api: "'stg_oldeworld_api' in (tags|list)"
  stg_oldeworld_clt: "'stg_oldeworld_clt' in (tags|list)"
  stg_oldeworld_pxy: "'stg_oldeworld_pxy' in (tags|list)"
  stg_oldeworld_nws: "'stg_oldeworld_nws' in (tags|list)"

  # Oldeworld Cluster -- PRD
  prd_oldeworld_all: "'prd' in (tags|list) and 'oldeworld' in (tags|list)"
  prd_oldeworld_api: "'prd_oldeworld_api' in (tags|list)"
  prd_oldeworld_clt: "'prd_oldeworld_clt' in (tags|list)"
  prd_oldeworld_pxy: "'prd_oldeworld_pxy' in (tags|list)"
  prd_oldeworld_nws: "'prd_oldeworld_nws' in (tags|list)"

compose:
  ansible_ssh_host: ipv4[0]
