# IMPORTANT: This file has to be be named linode.yml or linode.yaml
# See: https://github.com/ansible-collections/community.general/blob/011b2f8bdc2a042f0eb44739ff51ce425f391afa/plugins/inventory/linode.py#L274

plugin: community.general.linode # can be replaced with linode.cloud.instance, when they support Jinja2 template strings
access_token: "{{ lookup('env', 'LINODE_API_TOKEN') }}"

groups:
  # Test Instances
  test_all: "'test' in (tags|list)"

  # Staging Instances
  stg_all: "'stg' in (tags|list)"

  # Production Instances
  prd_all: "'prd' in (tags|list)"

  # Operations Instances
  ops_all: "'ops' in (tags|list)"

  # O11y Cluster
  o11y_all: "'o11y' in (tags|list)"
  managers: "'o11y_leader' in (tags|list)" # TODO: Refactor the naming of this group
  workers: "'o11y_worker' in (tags|list)" # TODO: Refactor the naming of this group

  # mintworld Cluster
  mintworld_all: "'mintworld' in (tags|list)"
  mintworld_nomad_servers:
    "'nomad_svr' in (tags|list) and 'mintworld' in (tags|list)"
  mintworld_consul_servers:
    "'consul_svr' in (tags|list) and 'mintworld' in (tags|list)"
  mintworld_nomad_workers:
    "'nomad_wkr' in (tags|list) and 'mintworld' in (tags|list)"

  # Oldeworld Cluster -- ALL
  oldeworld_all: "'oldeworld' in (tags|list)"

  # Oldeworld Cluster -- STG
  stg_oldeworld_all: "'stg' in (tags|list) and 'oldeworld' in (tags|list)"
  stg_oldeworld_api: "'stg_oldeworld_api' in (tags|list)"
  stg_oldeworld_api_old: "'stg_oldeworld_api' in (tags|list) and 'old_api' in (tags|list)"
  stg_oldeworld_api_new: "'stg_oldeworld_api' in (tags|list) and 'new_api' in (tags|list)"
  stg_oldeworld_clt: "'stg_oldeworld_clt' in (tags|list)"
  stg_oldeworld_pxy: "'stg_oldeworld_pxy' in (tags|list)"
  stg_oldeworld_nws: "'stg_oldeworld_nws' in (tags|list)"
  stg_oldeworld_jms: "'stg_oldeworld_jms' in (tags|list)"

  # Oldeworld Cluster -- PRD
  prd_oldeworld_all: "'prd' in (tags|list) and 'oldeworld' in (tags|list)"
  prd_oldeworld_api: "'prd_oldeworld_api' in (tags|list)"
  prd_oldeworld_api_old: "'prd_oldeworld_api' in (tags|list) and 'old_api' in (tags|list)"
  prd_oldeworld_api_new: "'prd_oldeworld_api' in (tags|list) and 'new_api' in (tags|list)"
  prd_oldeworld_clt: "'prd_oldeworld_clt' in (tags|list)"
  prd_oldeworld_pxy: "'prd_oldeworld_pxy' in (tags|list)"
  prd_oldeworld_nws: "'prd_oldeworld_nws' in (tags|list)"
  prd_oldeworld_jms: "'prd_oldeworld_jms' in (tags|list)"

  # Oldeworld Cluster -- Clients by Language - STG
  stg_oldeworld_clt_eng:
    "'stg' in (tags|list) and 'oldeworld' in (tags|list) and 'eng' in
    (tags|list) and 'clt' in (tags|list)"
  stg_oldeworld_clt_chn:
    "'stg' in (tags|list) and 'oldeworld' in (tags|list) and 'chn' in
    (tags|list) and 'clt' in (tags|list)"
  stg_oldeworld_clt_cnt:
    "'stg' in (tags|list) and 'oldeworld' in (tags|list) and 'cnt' in
    (tags|list) and 'clt' in (tags|list)"
  stg_oldeworld_clt_esp:
    "'stg' in (tags|list) and 'oldeworld' in (tags|list) and 'esp' in
    (tags|list) and 'clt' in (tags|list)"
  stg_oldeworld_clt_ger:
    "'stg' in (tags|list) and 'oldeworld' in (tags|list) and 'ger' in
    (tags|list) and 'clt' in (tags|list)"
  stg_oldeworld_clt_ita:
    "'stg' in (tags|list) and 'oldeworld' in (tags|list) and 'ita' in
    (tags|list) and 'clt' in (tags|list)"
  stg_oldeworld_clt_jpn:
    "'stg' in (tags|list) and 'oldeworld' in (tags|list) and 'jpn' in
    (tags|list) and 'clt' in (tags|list)"
  stg_oldeworld_clt_por:
    "'stg' in (tags|list) and 'oldeworld' in (tags|list) and 'por' in
    (tags|list) and 'clt' in (tags|list)"
  stg_oldeworld_clt_ukr:
    "'stg' in (tags|list) and 'oldeworld' in (tags|list) and 'ukr' in
    (tags|list) and 'clt' in (tags|list)"
  stg_oldeworld_clt_swa:
    "'stg' in (tags|list) and 'oldeworld' in (tags|list) and 'swa' in
    (tags|list) and 'clt' in (tags|list)"

  # Oldeworld Cluster -- Clients by Language - PRD
  prd_oldeworld_clt_eng:
    "'prd' in (tags|list) and 'oldeworld' in (tags|list) and 'eng' in
    (tags|list) and 'clt' in (tags|list)"
  prd_oldeworld_clt_chn:
    "'prd' in (tags|list) and 'oldeworld' in (tags|list) and 'chn' in
    (tags|list) and 'clt' in (tags|list)"
  prd_oldeworld_clt_cnt:
    "'prd' in (tags|list) and 'oldeworld' in (tags|list) and 'cnt' in
    (tags|list) and 'clt' in (tags|list)"
  prd_oldeworld_clt_esp:
    "'prd' in (tags|list) and 'oldeworld' in (tags|list) and 'esp' in
    (tags|list) and 'clt' in (tags|list)"
  prd_oldeworld_clt_ger:
    "'prd' in (tags|list) and 'oldeworld' in (tags|list) and 'ger' in
    (tags|list) and 'clt' in (tags|list)"
  prd_oldeworld_clt_ita:
    "'prd' in (tags|list) and 'oldeworld' in (tags|list) and 'ita' in
    (tags|list) and 'clt' in (tags|list)"
  prd_oldeworld_clt_jpn:
    "'prd' in (tags|list) and 'oldeworld' in (tags|list) and 'jpn' in
    (tags|list) and 'clt' in (tags|list)"
  prd_oldeworld_clt_por:
    "'prd' in (tags|list) and 'oldeworld' in (tags|list) and 'por' in
    (tags|list) and 'clt' in (tags|list)"
  prd_oldeworld_clt_ukr:
    "'prd' in (tags|list) and 'oldeworld' in (tags|list) and 'ukr' in
    (tags|list) and 'clt' in (tags|list)"
  prd_oldeworld_clt_swa:
    "'prd' in (tags|list) and 'oldeworld' in (tags|list) and 'swa' in
    (tags|list) and 'clt' in (tags|list)"

compose:
  ansible_ssh_host: ipv4[0]
