name: 'Setup Ansible'
description: 'Install ansible & other dependencies'

runs:
  using: 'composite'
  steps:
    - name: Setup UV
      shell: bash
      run: |
        # Install uv if not available
        if ! command -v uv >/dev/null 2>&1; then
          echo "Installing uv..."
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
        fi

        # Verify uv is available
        if ! command -v uv >/dev/null 2>&1; then
          echo "ERROR: uv installation failed"
          exit 1
        fi

        echo "uv version: $(uv --version)"

    - name: Setup Ansible and Dependencies
      shell: bash
      run: |
        # Use uv to install ansible and dependencies (matches local setup)
        uv sync

        # Activate venv and install ansible collections/roles
        source .venv/bin/activate
        ansible-galaxy install -r requirements.yml

        # Verify ansible is working
        ansible --version
