---
- name: Check the installation directory
  stat:
    path: "{{ azagent_dir }}"
  register: azagent_dir_stat

- name: Stop Azure DevOps agent service
  block:
    - name: Check azagent status
      shell:
        executable: /bin/bash
        cmd: |
          sudo ./svc.sh status
        chdir: "{{ azagent_dir }}"
      register: azagent_status_running
      ignore_errors: True

    - name: Stop azagent
      shell:
        executable: /bin/bash
        cmd: |
          sudo ./svc.sh stop
        chdir: "{{ azagent_dir }}"
      when: azagent_status_running.stdout.find('running') != -1 and azagent_status_running.stderr.find('command not found') == -1
      ignore_errors: True

    - name: Check azagent status
      shell:
        executable: /bin/bash
        cmd: |
          sudo ./svc.sh status
        chdir: "{{ azagent_dir }}"
      register: azagent_status_installed
      changed_when: False
      ignore_errors: True

    - name: Uninstall azagent
      shell:
        executable: /bin/bash
        cmd: |
          sudo ./svc.sh uninstall
        chdir: "{{ azagent_dir }}"
      when: (
        azagent_status_installed.stdout.find('not installed') != -1 or
        azagent_status_installed.stdout.find('dead') != -1
        ) and azagent_status_installed.stderr.find('command not found') == -1
      ignore_errors: True

    - name: Remove the agent from the pool
      shell:
        executable: /bin/bash
        cmd: |
          ./config.sh remove --unattended --auth pat --token '{{ agent_pat_token }}'
        chdir: "{{ azagent_dir }}"
      register: azagent_remove
  when: azagent_dir_stat.stat.exists

- name: Delete azagent directory
  become: true
  become_user: root
  become_method: sudo
  file:
    path: "{{ azagent_dir }}"
    state: absent
