---
- name: Stop Azure DevOps Pipeline Agent
  shell:
    cmd: |
      sudo ./svc.sh stop
    executable: /bin/bash
    chdir: '{{ azagent_dir }}'

- name: Update Env & Start Azure DevOps Pipeline Agent
  shell:
    cmd: |
      export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ]
      printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
      [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
      nvm version && echo PATH=$PATH && echo NVM_BIN=$NVM_BIN
      ./env.sh
      sudo ./svc.sh start
    executable: /bin/bash
    chdir: '{{ azagent_dir }}'
