#cloud-config
package_update: true
package_upgrade: true
package_reboot_if_required: true
packages:
  - unattended-upgrades
  - software-properties-common
users:
  - name: freecodecamp
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh_import_id:
      - raisedadead
      - gh:nhcarrigan
      - gh:ojeytonwilliams
      - gh:scissorsneedfoodtoo

final_message: 'Setup complete'
