---
- name: Install or Update NVM
  shell: |
    curl --silent "https://api.github.com/repos/nvm-sh/nvm/releases/latest" |
    grep '"tag_name":' |
    sed -E 's/.*"([^"]+)".*/\1/' |
    xargs -I % curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/%/install.sh |
    bash
  args:
    executable: /bin/bash
- name: Install or Update Node.js
  shell: |
    source ~/.nvm/nvm.sh
    if [[ {{ nodejs_version }} == "latest" ]]; then
      if [[ $(nvm version) == 'none' ]] ; then
        nvm install --lts --latest-npm --default
      else
        nvm install --lts --latest-npm --default --reinstall-packages-from=node
      fi
    else
      nvm install {{ nodejs_version }}
    fi
    echo "Node.js version $(node --version) installed."
  args:
    executable: /bin/bash
