---
- name: Install fCC logtool on Ubuntu
  hosts: all
  become: true
  become_method: sudo
  gather_facts: true

  tasks:
    - name: Create the logtool script
      copy:
        content: |

      owner: root
      group: root
      dest: /usr/local/bin/fcc-logtool.sh
      mode: 0755
