---
- name: Install AWS CLI on Ubuntu
  hosts: all
  become: true
  become_method: sudo
  gather_facts: true

  tasks:
    - name: Set fact for aarch64 or x86_64
      set_fact:
        arch: "{{ (ansible_architecture == 'aarch64') | ternary('aarch64', 'x86_64') }}"

    - name: Ensure /tmp/awscli directory exists
      file:
        path: /tmp/awscli
        state: directory
        owner: root
        group: root
        mode: 0755

    - name: Download and Extract AWS CLI
      unarchive:
        src: https://awscli.amazonaws.com/awscli-exe-linux-{{ arch }}.zip
        dest: /tmp/awscli
        remote_src: yes
        owner: root
        group: root
        mode: 0755

    - name: Install AWS CLI
      command: /tmp/awscli/aws/install --bin-dir /usr/local/bin --install-dir /usr/local/aws-cli --update
      args:
        creates: /usr/local/bin/aws

    - name: Verify AWS CLI Installation
      command: aws --version
      register: aws_cli_version

    - name: Debug AWS CLI Version
      debug:
        var: aws_cli_version.stdout

    - name: Clean up
      file: path=/tmp/awscli state=absent
