---
- name: Reboot
  hosts: all
  become: true
  become_method: sudo
  gather_facts: false

  tasks:
    - name: Reboot
      ansible.builtin.reboot:
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 180
        post_reboot_delay: 60
        test_command: uptime
