---
- name: Install Docker and Docker Compose on Ubuntu
  hosts: all
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
    stdout_callback: 'yaml'

  tasks:
    - name: Update apt package index
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Install prerequisite packages
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - python3-pip
          - python3-setuptools
          - software-properties-common
          - virtualenv
        state: present
        autoclean: true
        autoremove: true
        purge: true

    - name: Install Docker CE, CLI, Containerd and Compose
      ansible.builtin.shell: |
        set -e -o pipefail
        sudo mkdir -p /etc/apt/keyrings
        sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
        sudo echo \
          "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
          $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
        sudo apt-get update
        sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
      args:
        executable: /bin/bash
      become_method: sudo
      become: true
      register: docker_install
      changed_when: docker_install.stdout.find('Setting up docker-ce') != -1

    - name: Install Docker Module for Python
      pip:
        name: docker
