---
- name: Install common packages on Ubuntu
  hosts: all
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
    stdout_callback: "yaml"

  tasks:

    - name: Update apt package index
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Update all packages
      ansible.builtin.apt:
        upgrade: dist
        autoremove: true
        autoclean: true

    - name: Install common packages
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: present
        autoclean: true
        autoremove: true
        purge: true
      vars:
        packages:
          - curl
          - git
          - htop
          - vim
          - software-properties-common
          - build-essential
          - unzip
          - zip
          - tar

    - name: Disable automatic and security updates
      ansible.builtin.apt:
        name: unattended-upgrades
        state: absent
      vars:
        update_package_lists: false
        allowed_origins:
          - security
          - updates
          - proposed
          - backports
        package_blacklist:
          - '*'
