---
- name: Setup CNI plugin from GitHub release
  shell: |
    set -e
    set -x
    curl -L -o cni-plugins.tgz "https://github.com/containernetworking/plugins/releases/download/v1.0.0/cni-plugins-linux-$( [ $(uname -m) = aarch64 ] && echo arm64 || echo amd64)"-v1.0.0.tgz && \
    sudo mkdir -p /opt/cni/bin && \
    sudo tar -C /opt/cni/bin -xzf cni-plugins.tgz
  args:
    executable: /bin/bash

- name: Set up CNI plugin configuration (to persist across reboots)
  template:
    src: cni-plugin-bridge.conf.j2
    dest: /etc/sysctl.d/bridge.conf
    owner: root
    group: root
    mode: 0644

- name: Load CNI plugin configuration (to apply immediately)
  shell: |
    echo 1 | sudo tee /proc/sys/net/bridge/bridge-nf-call-arptables && \
    echo 1 | sudo tee /proc/sys/net/bridge/bridge-nf-call-ip6tables && \
    echo 1 | sudo tee /proc/sys/net/bridge/bridge-nf-call-iptables
  args:
    executable: /bin/bash
