---
- name: Create folder for NGINX docker setup
  file:
    path: /etc/nginx-nomad-http
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Copy docker-compose file for NGINX setup
  template:
    src: nginx-nomad-http--docker-compose.yml.j2
    dest: /etc/nginx-nomad-http/docker-compose.yml
    owner: root
    group: root
    mode: 0644

- name: Copy the nginx configuration file
  template:
    src: nginx-nomad-http--nginx.conf.j2
    dest: /etc/nginx-nomad-http/nginx.conf
    owner: root
    group: root
    mode: 0644
