---
- name: Check if Docker is installed
  stat:
    path: /usr/bin/docker
  register: docker_installed
  no_log: "{{ variable_no_log | default (true) }}"

- name: Check if Nomad is installed
  stat:
    path: /usr/bin/nomad
  register: nomad_installed
  no_log: "{{ variable_no_log | default (true) }}"

- name: Install Nomad if not installed using the role
  include_role:
    name: nomad
    tasks_from: install-nomad.yml
  when:
    nomad_installed.stat.exists == false and
    docker_installed.stat.exists == true

- name: Done Installing
  debug:
    msg: "Done Installing Nomad, continue to configure with additional playbooks."
