# tasks file for roles/swarm
---
- name: Gather network interfaces facts
  ansible.builtin.setup:
    gather_subset:
      - network
  no_log: "{{ variable_no_log | default (true) }}"
  when: inventory_hostname in groups['managers']

- name: Check if eth1 (private vlan) exists
  set_fact:
    eth1_exists: true
  when: inventory_hostname in groups['managers'] and "'eth1' in ansible_interfaces"

- name: Set the management IP address for swarm on managers
  set_fact:
    mgmt_listen_ip: "{{ eth1_exists | ternary( ansible_eth1.ipv4.address, ansible_default_ipv4.address) }}"
  when: inventory_hostname in groups['managers']

- name: Initialize a Docker Swarm
  community.docker.docker_swarm:
    state: present
    advertise_addr: "{{ mgmt_listen_ip }}"
    listen_addr: "{{ mgmt_listen_ip }}:2377"
  when: inventory_hostname == groups['managers'][0]
  no_log: "{{ variable_no_log | default (true) }}"

- name: Retrieve the Swarm Info
  community.docker.docker_swarm_info:
    nodes: true
  register: swarm_info
  when: inventory_hostname == groups['managers'][0]
  no_log: "{{ variable_no_log | default (true) }}"

  # TODO: Add checks and add more managers if needed
  # - name: Set useful information on Managers as Facts
  # - name: Join Swarm as manager using token

- name: Set useful information on Workers as Facts
  set_fact:
    swarm_join_token_worker: "{{ hostvars[groups['managers'][0]]['swarm_info']['swarm_facts']['JoinTokens']['Worker'] }}"
    swarm_manager_addr: "{{ hostvars[groups['managers'][0]]['mgmt_listen_ip'] }}"
  when: inventory_hostname in groups['workers']
  no_log: "{{ variable_no_log | default (true) }}"

- name: Join Swarm as worker using token
  community.docker.docker_swarm:
    state: join
    advertise_addr: "{{ ansible_default_ipv4.address }}"
    join_token: "{{ swarm_join_token_worker }}"
    remote_addrs: [
      "{{ swarm_manager_addr }}"
    ]
  when: inventory_hostname in groups['workers']

- name: List Swarm Nodes
  community.docker.docker_swarm_info:
    nodes: true
  when: inventory_hostname == groups['managers'][0]
  register: result
  no_log: "{{ variable_no_log | default (true) }}"

- name: Print Swarm Nodes
  debug:
    msg: "{{ result.nodes }}"
  when: inventory_hostname in groups['managers']
