---
- name: Initialize Olde World Cluster - Clients
  hosts: '{{ variable_host | default("null") }}'
  become: true
  become_user: freecodecamp
  gather_facts: false
  vars:
    client_groups:
      ['chn', 'cnt', 'eng', 'esp', 'ger', 'ita', 'jpn', 'por', 'ukr']
    client_hosts: ['1', '2']
    client_env: '{{ variable_client_env }}'
    agent_version: '{{ variable_agent_version | default("3.220.5") }}'
  tasks:
    # - name: Create deployment groups from list of items
    #   add_host:
    #     groups: '{{ client_env }}_oldeworld_clt{{ item[0] }}'
    #     name: '{{ client_env }}-vm-oldeworld-clt{{ item[0] }}-{{ item[1] }}'
    #   with_nested:
    #     - '{{ client_groups }}'
    #     - '{{ client_hosts }}'

    # - name: Print deployment groups
    #   debug:
    #     msg: '{{ groups[client_env + "_oldeworld_clt" + item] }}'
    #   with_items: '{{ client_groups }}'
    - name: Install or Update Node.js
      include_role:
        name: nodejs

    - name: Uninstall and remove azagent
      include_role:
        name: azagent
        tasks_from: delete-azagent.yml
      vars:
        agent_deploymentgroup_name: '{{ client_env }}-dp-clt{{ item[0] }}'
        agent_machine_name:
          '{{ client_env }}-vm-oldeworld-clt-{{ item[0] }}-{{ item[1] }}'
        agent_project_name: 'freeCodeCamp'
        agent_pat_token: '{{ variable_pat_token }}'
      loop: '{{ client_groups | product(client_hosts) | list }}'
      when:
        inventory_hostname == client_env + "-vm-oldeworld-clt" + item[0] + "-" +
        item[1]

    - name: Install azagent
      include_role:
        name: azagent
        tasks_from: install-azagent.yml
      vars:
        agent_deploymentgroup_name: '{{ client_env }}-dp-clt{{ item[0] }}'
        agent_machine_name:
          '{{ client_env }}-vm-oldeworld-clt-{{ item[0] }}-{{ item[1] }}'
        agent_project_name: 'freeCodeCamp'
        agent_pat_token: '{{ variable_pat_token }}'
        agent_download_url:
          'https://vstsagentpackage.azureedge.net/agent/{{ agent_version
          }}/vsts-agent-linux-x64-{{ agent_version }}.tar.gz'
      loop: '{{ client_groups | product(client_hosts) | list }}'
      when:
        inventory_hostname == client_env + "-vm-oldeworld-clt" + item[0] + "-" +
        item[1]
