---
- name: Tailscale - Connect to Tailscale Network
  hosts: '{{ variable_host | default("null") }}'
  become: true
  gather_facts: false
  tasks:
    - name: Add Tailscale to Network
      shell:
        cmd: |
          tailscale up \
          --authkey "{{ lookup('env', 'TAILSCALE_AUTH_KEY') }}" \
          --hostname {{ inventory_hostname }} \
          --force-reauth \
          --reset \
          --ssh
        executable: /bin/bash
      no_log: true
      changed_when: true
      ignore_errors: true
      register: tailscale_up

    - name: Print error message if Tailscale failed
      debug:
        msg: "{{ tailscale_up.stderr }}"
      when: tailscale_up.rc != 0

    - name: Check if Tailscale is Connected
      shell:
        cmd: |
          tailscale status --json | jq -r '.Self.Online'
        executable: /bin/bash
      register: tailscale_status

    - name: Check DNS name
      shell:
        cmd: |
          tailscale status --json | jq -r '.Self.DNSName'
        executable: /bin/bash
      register: tailscale_dns

    - name: Print Tailscale Status
      debug:
        msg: |
          Tailscale Status: {{ tailscale_status.stdout }}
          Tailscale DNS: {{ tailscale_dns.stdout }}
