---
- name: Tailscale - Add Cert for Tailscale Network (https access)
  hosts: '{{ variable_host | default("null") }}'
  become: true
  gather_facts: false
  tasks:
    - name: Run Tailscale Cert
      shell:
        cmd: |
          tailscale cert {{ inventory_hostname }}.{{ variable_tailnet_dns_name }}
        executable: /bin/bash
      no_log: true
      changed_when: true
      ignore_errors: true
