---
- name: Initialize a O11y Cluster
  hosts: all
  become: true
  roles:
    - ubuntu # Update the OS and reboot the server
    - dns # Configure ansible facts for networking info lookup
    - docker # Intialize docker and docker swarm cluster
