---
- name: Datacenter Cluster -- Startup
  hosts: '{{ variable_host | default("null") }}'
  become: true
  vars:
    - nomad_svr: '{{ variable_nomad_servers_grp | default("mintworld_nomad_servers") }}'
    - consul_svr: '{{ variable_consul_servers_grp | default("mintworld_consul_servers") }}'
    - cluster_wkr: '{{ variable_cluster_workers_grp | default("mintworld_cluster_workers") }}'
    - restart_services: '{{ variable_restart_services | default(false) }}'

  tasks:
    - name: Consul Servers - Startup Consul Services
      block:
        - name: Enable and Start Consul Services on Consul Servers
          service: name=consul state=started enabled=yes
          when: restart_services == false

        - name: Restart Consul Services on Consul Servers
          service: name=consul state=restarted
          when: restart_services == true
      when: inventory_hostname in groups[consul_svr]


    - name: Nomad Servers - Startup Consul and Nomad Services
      block:
        - name: Enable and Start Consul Services on Nomad Servers
          service: name=consul state=started enabled=yes
          when: restart_services == false

        - name: Restart Consul Services on Nomad Servers
          service: name=consul state=restarted
          when: restart_services == true

        - name: Enable and Start Nomad Services on Nomad Servers
          service: name=nomad state=started enabled=yes
          when: restart_services == false

        - name: Restart Nomad Services on Nomad Servers
          service: name=nomad state=restarted
          when: restart_services == true
      when: inventory_hostname in groups[nomad_svr]

    - name: Nomad Servers - Startup NGINX Service for HTTP access (Web UI and API)
      block:
        - name: Start NGINX Service
          command: docker compose -f /etc/nginx-nomad-http/docker-compose.yml up -d
      when: inventory_hostname in groups[nomad_svr]

    - name: Startup Cluster Workers
      block:
        - name: Enable and Start Consul Services on Cluster Workers
          service: name=consul state=started enabled=yes
          when: restart_services == false

        - name: Restart Consul Services on Cluster Workers
          service: name=consul state=restarted
          when: restart_services == true

        - name: Enable and Start Nomad Services on Cluster Workers
          service: name=nomad state=started enabled=yes
          when: restart_services == false

        - name: Restart Nomad Services on Cluster Workers
          service: name=nomad state=restarted
          when: restart_services == true
      when: inventory_hostname in groups[cluster_wkr]
