---
- name: Configure NGINX on the Oldeworld Cluster
  hosts: '{{ variable_host | default("null") }}'
  become: true
  vars:
    pxy_env: '{{ variable_pxy_env }}'
  roles:
    - dns # Configure ansible facts for networking info lookup

  tasks:
    - name: Configure Nginx instances
      include_tasks: roles/nginx/tasks/config-nginx.yml
