---
- name: Initialize O11y Cluster
  hosts: o11y_all
  become: true
  roles:
    # - ubuntu # Update the OS and reboot the server
    - dns # Configure ansible facts for networking info lookup
    - docker # Intialize docker
    - docker-swarm # Initialize a docker swarm cluster
