---
- name: Tailscale - Connect
  hosts: '{{ variable_host | default("null") }}'
  gather_facts: false
  tasks:
    - name: Run Tailscale Up
      shell:
        cmd: |
          tailscale up \
          --authkey "{{ lookup('env', 'TAILSCALE_AUTH_KEY') }}" \
          --hostname "{{ inventory_hostname }}" \
          --force-reauth
        executable: /bin/bash
      no_log: true
      changed_when: true
      ignore_errors: true

    - name: Check if Tailscale is Connected
      shell:
        cmd: |
          tailscale status --json | jq -r '.Self.Online'
        executable: /bin/bash
      register: tailscale_status

    - name: Check DNS name
      shell:
        cmd: |
          tailscale status --json | jq -r '.Self.DNSName'
        executable: /bin/bash
      register: tailscale_dns

    - name: Print Tailscale Status
      debug:
        msg: |
          Tailscale Status: {{ tailscale_status.stdout }}
          Tailscale DNS: {{ tailscale_dns.stdout }}
