---
- name: Initialize Olde World Cluster - Ghost
  hosts: '{{ variable_host | default("null") }}'
  become: true
  become_user: freecodecamp
  gather_facts: false
  tasks:
    - name: Install or Update Node.js
      include_role:
        name: nodejs
      vars:
        nodejs_version: 'v14.21.3'
