---
- name: AWS SSM Test
  hosts: '{{ variable_host | default("null") }}'
  gather_facts: false
  vars:
    ansible_aws_ssm_bucket_name: "{{ lookup('env', 'AWS_SSM_BUCKET_NAME') }}"
    ansible_aws_ssm_region: "{{ lookup('env', 'AWS_SSM_REGION') }}"

  tasks:
    - name: Run shell commands for tests
      shell: |
        set -e -o pipefail
        printf "Hostname: %s\n" "$(hostname)"
        printf "Working Directory: %s\n" "$(pwd)"
        printf "Current User: %s\n" "$(whoami)"
      args:
        executable: /bin/bash
      register: shell_output

    - name: Debugging
      debug:
        msg: |
          --
          Output:
          {{ shell_output.stdout }}
          --
          Error:
          {{ shell_output.stderr }}
          --
