---
- name: Generate Prefix for Hostnames
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Generate a random string for the hostname prefix
      set_fact:
        global_prefix: "{{ query('community.general.random_string', upper=false, lower=false, override_special='0123456789ABCDEF', numbers=false) | first }}"
      run_once: true

- name: Tailscale - Connect to Tailscale Network
  hosts: '{{ variable_host | default("null") }}'
  become: true
  gather_facts: false
  vars:
    prefix: "{{ hostvars['localhost']['global_prefix'] }}"
  tasks:
    - name: Add Tailscale to Network
      shell:
        cmd: |
          tailscale up \
          --authkey "{{ lookup('env', 'TAILSCALE_AUTH_KEY') }}" \
          --hostname "{{ inventory_hostname }}" \
          --advertise-tags "tag:{{ prefix }}" \
          --force-reauth
        executable: /bin/bash
      no_log: true
      changed_when: true
      ignore_errors: true

    - name: Check if Tailscale is Connected
      shell:
        cmd: |
          tailscale status --json | jq -r '.Self.Online'
        executable: /bin/bash
      register: tailscale_status

    - name: Check DNS name
      shell:
        cmd: |
          tailscale status --json | jq -r '.Self.DNSName'
        executable: /bin/bash
      register: tailscale_dns

    - name: Print Tailscale Status
      debug:
        msg: |
          Tailscale Status: {{ tailscale_status.stdout }}
          Tailscale DNS: {{ tailscale_dns.stdout }}
