---
- name: Create Groups from Nomad Instances
  hosts: '{{ variable_host | default("null") }}'
  become: true
  gather_facts: false
  tasks:
    - name: Set up Nomad Server Config
      include_role:
        name: nomad
        tasks_from: config-nomad-server.yml
      when: '"ldr" in inventory_hostname'

    - name: Set up Nomad Client Config
      include_role:
        name: nomad
        tasks_from: config-nomad-client.yml
      when: '"wkr" in inventory_hostname'

    - name: Set up Nomad Services on Servers
      include_role:
        name: nomad
        tasks_from: config-systemd-server.yml
      when: '"ldr" in inventory_hostname'

    - name: Set up Nomad Services on Clients
      include_role:
        name: nomad
        tasks_from: config-systemd-client.yml
      when: '"wkr" in inventory_hostname'
