#cloud-config
users:
  - name: freecodecamp
    groups: sudo
    shell:  /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh_import_id:
      - gh:camperbot
      - raisedadead
runcmd:
  - usermod -aG docker freecodecamp
  # This sections should be the last in the list because it involves restarting the ssh service,
  # which may prevent commands from running after it in certain scenarios.
  - sed -i -e '/^PermitRootLogin/s/^.*$/PermitRootLogin no/' /etc/ssh/sshd_config
  - sed -i -e '/^PasswordAuthentication/s/^.*$/PasswordAuthentication no/' /etc/ssh/sshd_config
  - sed -i -e '$aAllowUsers freecodecamp' /etc/ssh/sshd_config
  - restart ssh"}
final_message: 'Setup complete'
