#cloud-config
users:
  - name: freecodecamp
    groups: sudo
    shell:  /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh_import_id:
      - gh:camperbot
      - raisedadead
runcmd:
  - sudo sed -i -e '/^PermitRootLogin/s/^.*$/PermitRootLogin no/' /etc/ssh/sshd_config
  - sudo sed -i -e '/^PasswordAuthentication/s/^.*$/PasswordAuthentication no/' /etc/ssh/sshd_config
  - sudo sed -i -e '$aAllowUsers freecodecamp' /etc/ssh/sshd_config
  - sudo restart ssh"}
  - sudo usermod -aG docker freecodecamp
  - sudo apt update -qq
final_message: 'Setup complete'
