---
- name: Git Update
  hosts: "{{ variable_host | default('stg_client') }}"

  tasks:
    - name: Update Git Repository
      ansible.builtin.git:
        name: https://github.com/freeCodeCamp/client-config.git
        dest: /home/freecodecamp/client
        clone: no
        update: yes
        single_branch: yes
        version: master
