---
- name: Git Update
  hosts: "{{ variable_host | default('stg_client') }}"

  tasks:
    - name: Update Git Repository
      git:
        name: https://github.com/freeCodeCamp/client-config.git
        dest: /home/freecodecamp/client
        clone: no
        update: yes
        single_branch: yes
        version: master

    - name: PM2 Update
      shell: |
        echo "Reload and save with PM2.." \
        && export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] \
        && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")" \
        && [ -s "$NVM_DIR/nvm.sh" ] \
        && \. "$NVM_DIR/nvm.sh" \
        && pm2 reload all --update-env \
        && pm2 save \
        && echo "done.." && exit 0
