- name: reboot virtual machines
  hosts: "{{ variable_host | default('prd_client') }}"
  gather_facts: false
  tasks:
    - name: capture directories older than 15 days
      find:
        paths: /home/freecodecamp/client/releases
        recurse: no
        file_type: directory
        age: 15d
      register: files_to_delete

    - name: remove directories older than 15 days
      file:
        path: '{{ item.path }}'
        state: absent
      with_items: '{{ files_to_delete.files }}'
