- name: apt-update packages and kernel on virtual machines
  hosts: "{{ variable_host | default('servers') }}"
  become: true
  become_user: root
  tasks:
    - name: Update apt repo and cache on all Debian/Ubuntu virtual machines
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Upgrade all packages on servers
      apt: upgrade=dist force_apt_get=yes
