- name: check uptime on virtual machines
  hosts: "{{ variable_host | default('all') }}"
  gather_facts: false
  become_user: root
  tasks:
    - name: execute the uptime command over command module
      register: uptimeoutput
      command: 'uptime'

    - debug:
        var: uptimeoutput.stdout_lines
