name: Ansible --02- Houskeeping

on:
  workflow_dispatch:
  schedule:
    - cron: '5 0 * * 3,6' # 00:05 UTC on Wednesdays and Saturdays (6 hour maintenance window)

defaults:
  run:
    working-directory: './ansible'

jobs:
  test:
    name: Ansible Test
    runs-on: ubuntu-latest
    env:
      LINODE_API_TOKEN: ${{ secrets.LINODE_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@09d2acae674a48949e3602304ab46fd20ae0c42f

      - name: Setup Ansible Dependencies
        uses: ./.github/actions/setup-ansible

      - name: Validate Inventory
        uses: ./.github/actions/validate-inventory
        with:
          inventory: linode.yml

  uptime:
    name: Uptime
    needs: test
    strategy:
      fail-fast: false
      matrix:
        host_groups:
          - ops_all
          - stg_oldeworld_api
          - prd_oldeworld_api
          - stg_oldeworld_pxy
          - prd_oldeworld_pxy
          - stg_oldeworld_nws
          - prd_oldeworld_nws
          - stg_oldeworld_jms
          - prd_oldeworld_jms
          - stg_oldeworld_clt
          - prd_oldeworld_clt_eng
          - prd_oldeworld_clt_chn
          - prd_oldeworld_clt_cnt
          - prd_oldeworld_clt_esp
          - prd_oldeworld_clt_ger
          - prd_oldeworld_clt_ita
          - prd_oldeworld_clt_jpn
          - prd_oldeworld_clt_por
          - prd_oldeworld_clt_ukr
          - prd_oldeworld_clt_swa

    uses: ./.github/workflows/ansible--uptime.yml
    with:
      hosts: ${{ matrix.host_groups }}
      verbosity: '-v'
      serial: 3
    secrets:
      LINODE_TOKEN: ${{ secrets.LINODE_TOKEN }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

  wait-on-uptime:
    name: Wait on Uptime
    needs: uptime
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@09d2acae674a48949e3602304ab46fd20ae0c42f

      - name: Wait for 300 seconds
        uses: ./.github/actions/wait
        with:
          seconds: '300'

  update:
    name: Update
    needs: wait-on-uptime
    strategy:
      fail-fast: false
      matrix:
        host_groups:
          - ops_all
          - stg_oldeworld_api
          - prd_oldeworld_api
          - stg_oldeworld_pxy
          - prd_oldeworld_pxy
          - stg_oldeworld_nws
          - prd_oldeworld_nws
          - stg_oldeworld_jms
          - prd_oldeworld_jms
          - stg_oldeworld_clt
          - prd_oldeworld_clt_eng
          - prd_oldeworld_clt_chn
          - prd_oldeworld_clt_cnt
          - prd_oldeworld_clt_esp
          - prd_oldeworld_clt_ger
          - prd_oldeworld_clt_ita
          - prd_oldeworld_clt_jpn
          - prd_oldeworld_clt_por
          - prd_oldeworld_clt_ukr
          - prd_oldeworld_clt_swa

    uses: ./.github/workflows/ansible--update.yml
    with:
      hosts: ${{ matrix.host_groups }}
      verbosity: '-v'
      serial: 1
    secrets:
      LINODE_TOKEN: ${{ secrets.LINODE_TOKEN }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

  wait-on-update:
    name: Wait on Update
    needs: update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@09d2acae674a48949e3602304ab46fd20ae0c42f

      - name: Wait for 300 seconds
        uses: ./.github/actions/wait
        with:
          seconds: '300'

  reboot-web:
    name: Reboot Ingress
    needs: wait-on-update
    strategy:
      fail-fast: false
      matrix:
        host_groups:
          - stg_oldeworld_pxy
          - prd_oldeworld_pxy
    uses: ./.github/workflows/ansible--reboot.yml
    with:
      hosts: ${{ matrix.host_groups }}
      verbosity: '-v'
      serial: 1
    secrets:
      LINODE_TOKEN: ${{ secrets.LINODE_TOKEN }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

  wait-on-reboot-web:
    name: Wait on Reboot (Web)
    needs: reboot-web
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@09d2acae674a48949e3602304ab46fd20ae0c42f

      - name: Wait for 300 seconds
        uses: ./.github/actions/wait
        with:
          seconds: '300'

  reboot:
    name: Reboot
    needs: wait-on-reboot-web
    strategy:
      fail-fast: false
      matrix:
        host_groups:
          - ops_all
          - stg_oldeworld_api
          - prd_oldeworld_api
          - stg_oldeworld_nws
          - prd_oldeworld_nws
          - stg_oldeworld_jms
          - prd_oldeworld_jms
          - stg_oldeworld_clt
          - prd_oldeworld_clt_eng
          - prd_oldeworld_clt_chn
          - prd_oldeworld_clt_cnt
          - prd_oldeworld_clt_esp
          - prd_oldeworld_clt_ger
          - prd_oldeworld_clt_ita
          - prd_oldeworld_clt_jpn
          - prd_oldeworld_clt_por
          - prd_oldeworld_clt_ukr
          - prd_oldeworld_clt_swa

    uses: ./.github/workflows/ansible--reboot.yml
    with:
      hosts: ${{ matrix.host_groups }}
      verbosity: '-v'
      serial: 1
    secrets:
      LINODE_TOKEN: ${{ secrets.LINODE_TOKEN }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
