name: Ansible CI Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      inventory:
        description: 'Inventory file to validate'
        type: choice
        required: true
        default: 'linode.yml'
        options:
          - 'linode.yml'
      verbosity:
        description: 'Verbosity level for logs'
        type: choice
        required: true
        default: '-v'
        options:
          - '-v'
          - '-vv'
          - '-vvv'

jobs:
  test:
    name: Ansible CI Test
    runs-on: ubuntu-latest
    env:
      WORKING_DIR: './ansible'
      LINODE_API_TOKEN: ${{ secrets.LINODE_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@09d2acae674a48949e3602304ab46fd20ae0c42f

      - name: Setup Ansible Dependencies
        uses: ./.github/actions/setup-ansible

      - name: Validate Inventory
        uses: ./.github/actions/validate-inventory
        with:
          inventory: ${{ inputs.inventory || 'linode.yml' }}

      - name: Test Basic Ansible Commands
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          # Test ansible commands work with installed dependencies
          ansible --version
          ansible-lint --version
          ansible-inventory --help >/dev/null
          echo "SUCCESS: All ansible commands working with CI setup"
