name: Ansible --04- Uptime

on:
  workflow_call:
    inputs:
      hosts:
        description: 'The value for the variable_host argument'
        type: string
        required: true
      verbosity:
        description: 'The verbosity level for logs'
        type: string
      serial:
        description: 'The value for the variable_serial argument'
        type: number
    secrets:
      SSH_PRIVATE_KEY:
        description: 'The SSH private key for the Ansible user'
        required: true
      LINODE_TOKEN:
        description: 'The Linode API token'
        required: true
  workflow_dispatch:
    inputs:
      hosts:
        description: 'The value for the variable_host argument'
        type: string
        required: true
        default: 'none'
      verbosity:
        description: 'The verbosity level for logs'
        type: choice
        required: true
        default: '-v'
        options:
          - '-v'
          - '-vv'
          - '-vvv'
      serial:
        description: 'The value for the variable_serial argument'
        type: number
        required: true
        default: 1

defaults:
  run:
    working-directory: './ansible'

jobs:
  run_playbook:
    name: Run Play
    runs-on: ubuntu-latest
    env:
      LINODE_API_TOKEN: ${{ secrets.LINODE_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@09d2acae674a48949e3602304ab46fd20ae0c42f

      - name: Setup Ansible and Dependencies
        uses: ./.github/actions/setup-ansible

      - name: Set up SSH key
        uses: ./.github/actions/setup-ssh
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Play -- Uptime
        run: |
          ansible-playbook -i inventory/linode.yml \
          play-any--uptime.yml \
          --private-key=~/.ssh/id_for_ansible.pem \
          -e '{"variable_host": "${{ inputs.hosts }}", "variable_serial": ${{ inputs.serial }}}' \
          ${{ inputs.verbosity }}
