name: Ansible -- Uptime

on:
  push:
  workflow_dispatch:
    inputs:
      hosts:
        description: 'The value for the variable_host argument'
        required: true
        default: 'none'

      verbosity:
        description: 'The verbosity level for logs'
        required: true
        type: choice
        default: '-v'
        options:
          - '-v'
          - '-vv'
          - '-vvv'

jobs:
  run_playbook:
    name: Run Ansible Playbook
    runs-on: ubuntu-latest
    env:
      WORKING_DIR: './ansible'
      LINODE_API_TOKEN: ${{ secrets.LINODE_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744

      - name: Setup Ansible and Dependencies
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          make install
          ansible --version

      - name: List Ansible Inventory
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          ansible-inventory --graph -v

      # - name: Connect with Tailscale
      #   uses: tailscale/github-action@v2
      #   with:
      #     oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
      #     oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
      #     tags: tag:ci

      # - name: Ansible Playbook -- Uptime
      #   working-directory: ${{ env.WORKING_DIR }}
      #   run: |
      #     ansible-playbook play-any--uptime.yml -e "variable_host=${{ github.event.inputs.hosts }}" ${{ github.event.inputs.verbosity }}
