name: CI - Node.js Test
on:
  push:
    branches-ignore:
      - 'renovate/**'
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout Source Files
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # tag=v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Lint Source Files
        run: |
          cd tf-cdk-ts
          npm ci
          npm run lint --if-present

  test:
    name: Test
    needs: lint
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout Source Files
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # tag=v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1 # tag=v2.0.3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Install Doppler CLI
        uses: dopplerhq/cli-action@41106dbef2e821dcf2250b0c936a616a438a278a # tag=v2

      - name: Run Tests
        run: |
          cd tf-cdk-ts
          npm ci
          export HISTIGNORE='doppler run*' # Prevent command with Service Token being recorded in bash history
          doppler run --token=$DOPPLER_TOKEN --project=infra --config=github -- npm run build
          echo ""
          echo ""
          echo "!!!! -------- Running tests is broken on CI, works locally though... -------- !!!!"
          echo ""
          echo ""
          exit 0
        #   doppler run --token=$DOPPLER_TOKEN --project=infra --config=github -- npm run test
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
