name: Packer -- Azure

on:
  workflow_dispatch:
    inputs:
      region:
        description: 'the region to build the image in'
        required: true
        default: 'eastus'
        type: choice
        options:
          - 'eastus'
          - 'westus'
          - 'centralus'
      ubuntu-flavor:
        description: 'the Ubuntu flavor to build the image in'
        required: true
        default: 'ubuntu-20.04'
        type: choice
        options:
          - 'ubuntu-22.04'
          - 'ubuntu-20.04'
          - 'ubuntu-18.04'
      child_image:
        description: 'the child image to build'
        required: true
        default: 'none'
        type: choice
        options:
          - 'none'
          - 'nginx'
          - 'nomad'

jobs:
  build-images:
    name: Build Images
    runs-on: ubuntu-latest

    env:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    outputs:
      output-build-ubuntu-image:
        ${{ steps.build-ubuntu-image.outputs.ubuntu_artifact_name }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3

      # Packer's official GitHub Actions are unstable & outdated, use a community action instead
      - name: Use latest Packer
        uses: hashicorp-contrib/setup-packer@ee5bed669b01ca73e42651206470fc355a60400d # tag=v2

      - name: Check Version
        run: |
          echo "Packer version: $(packer version)"

      - name: Build Ubuntu Image
        id: build-ubuntu-image
        run: |
          IMAGE_OFFER='0001-com-ubuntu-server-focal'
          IMAGE_SKU='22_04-LTS-gen2'
          case "${{ inputs.ubuntu-flavor }}" in
            ubuntu-22.04)
              IMAGE_OFFER='0001-com-ubuntu-server-jammy'
              IMAGE_SKU='22_04-LTS-gen2'
              ;;
            ubuntu-20.04)
              IMAGE_OFFER='0001-com-ubuntu-server-focal'
              IMAGE_SKU='20_04-LTS-gen2'
              ;;
            ubuntu-18.04)
              IMAGE_OFFER='0001-com-ubuntu-server-bionic'
              IMAGE_SKU='18_04-LTS-gen2'
              ;;
          esac

          packer init \
          -var location=${{ inputs.region }} \
          -var image_offer=${IMAGE_OFFER} \
          -var image_sku=${IMAGE_SKU} \
          ./packer/azure/ubuntu.pkr.hcl

          packer validate \
          -var image_offer=${IMAGE_OFFER} \
          -var image_sku=${IMAGE_SKU} \
          -var location=${{ inputs.region }} \
          ./packer/azure/ubuntu.pkr.hcl

          packer build \
          -var location=${{ inputs.region }} \
          -var image_offer=${IMAGE_OFFER} \
          -var image_sku=${IMAGE_SKU} \
          ./packer/azure/ubuntu.pkr.hcl

          UBUNTU_ARTIFACT_NAME=$(cat manifest.json | jq '.builds[].artifact_id' | sed -r 's|.*/(.*)"$|\1|')
          echo Building the next image with: $UBUNTU_ARTIFACT_NAME
          echo "::set-output name=ubuntu_artifact_name::$UBUNTU_ARTIFACT_NAME"

      - name: Build Child Image
        if: ${{ inputs.child_image != 'none' }}
        id: build-child-image
        run: |
          packer init \
          -var location=${{ inputs.region }} \
          -var custom_managed_image_name=${{ steps.build-ubuntu-image.outputs.ubuntu_artifact_name }} \
          ./packer/azure/${{ inputs.child_image }}.pkr.hcl

          packer validate \
          -var location=${{ inputs.region }} \
          -var custom_managed_image_name=${{ steps.build-ubuntu-image.outputs.ubuntu_artifact_name }} \
          ./packer/azure/${{ inputs.child_image }}.pkr.hcl

          packer build \
          -var location=${{ inputs.region }} \
          -var custom_managed_image_name=${{ steps.build-ubuntu-image.outputs.ubuntu_artifact_name }} \
          ./packer/azure/${{ inputs.child_image }}.pkr.hcl
