name: Packer -- Linode

on: workflow_dispatch

jobs:
  build-ubuntu-image:
    name: Build Ubuntu Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4

      # Packer's official GitHub Actions are unstable & outdated, use a community action instead
      - name: Use latest Packer
        uses: hashicorp-contrib/setup-packer@792b061950558f07fd3f2de9a194ddc4441f8ddf # v3

      - name: Check Version
        run: |
          echo "Packer version: $(packer version)"

      - name: Check formating
        run: |
          terraform fmt -check -recursive -diff \
          ./packer/linode

      - name: Build Ubuntu Image
        id: build-ubuntu-image
        env:
          LINODE_API_TOKEN: ${{ secrets.LINODE_TOKEN }}
        run: |
          packer init \
          ./packer/linode/ubuntu.pkr.hcl

          packer validate \
          ./packer/linode/ubuntu.pkr.hcl

          packer build \
          ./packer/linode/ubuntu.pkr.hcl
