name: Packer -- Linode

on:
  workflow_dispatch

jobs:
  build-ubuntu-image:
    name: Build Ubuntu Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      # Packer's official GitHub Actions are unstable & outdated, use a community action instead
      - name: Use latest Packer
        uses: hashicorp-contrib/setup-packer@ee5bed669b01ca73e42651206470fc355a60400d # tag=v2

      - name: Check Version
        run: |
          echo "Packer version: $(packer version)"

      - name: Check formating
        run: |
          terraform fmt -check -recursive -diff \
          ./packer/linode

      - name: Build Ubuntu Image
        id: build-ubuntu-image
        env:
          LINODE_TOKEN: ${{ secrets.LINODE_TOKEN }}
        run: |
          packer init \
          ./packer/linode/ubuntu.pkr.hcl

          packer validate \
          ./packer/linode/ubuntu.pkr.hcl

          packer build \
          ./packer/linode/ubuntu.pkr.hcl
